[gcp_service_account]
type = "service_account"
project_id = "mr-league-cloud"
private_key_id = "da2dbaa2ee27e225523142337b7a242b8efdbf3c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDtL0aRy4UMQoh1
NDxjfiwL/yaxIOALUavlPcBbl+Ik06NkfcTYbkt5tNL8mfySRLwvr8Oq/FEGgsp7
Or44lJ0fxIro3wa4BEXoeDi9eBUdW+EUTKac/ksipOGVw+nSFnOq7wIARECIV2dV
TbjgiNEzdkn5AN1CqimAb2hN1wyw3BEamIFIqmF+Xni+K/VeZ4DMfmtAL7qKMqo/
eDDjg9JF3+6J8c8A4C4X40YqWIiP10Laln5p1mcFP3HVpYTKV5iPcKaehO+PbUhr
Al893P12TFSJNP2id7/XB+utwkkI5C0nKDA7vBzcWcX11RVh6tbIvgsWp/FWbxAQ
e5wh3BgzAgMBAAECggEAcxxbHP4Po9wUewFvf3/oI6hg4F1KruOjz92Q4kML24Cl
T2ukob+hvL8QGM0pIdnfFSuyBGVxc339hCIF2NLzkMvj+NHo4l0cio7yRq4lXTrO
uXnb8NyPnZA09WkALVh9KYvWxkdZpHH68hEG9V4hXd7+Vq1fNO/9tVocXo7Ml3Y/
Wv9FcX30IaYoE/E6e+YfonmwQAF6FI67PYi0reO5Noei4dkToxcixbn9QYpPZFgO
zqp5i7nKgk3zJ4fRNbO9k8YgvSfZrDnf1c3W439dDlylAMopOqnrheFLz9f0z4KY
jpWgIPQn06pPaa3RSBOiFnoLYBfdwy3sjslZ2RxWwQKBgQD46Vg6R2XVYxmh5D37
fBOimZmqTuZfug8rv3vEOSoy8gPPJR24V2PDC2dPQeBMxTytfkC3MQDvse11cv+r
1mLT6oL0SiZeeEQWumOI5VKGxWPfkhbvfJDdQ8YqffEawaLEpWwJ3IXX89173noG
+1KVDeKH1Rs4s95+MwYEMFqrwQKBgQDz8HAq3FRIDNfnGMNZ1+RCxSjQwKifQz6C
2R4P6nNSKbbWf0ffbkUOdkYaWaQ3T6QE8AWYfWTLgG/5vdPRzTK6g8+DlKMmnjea
0PFIQ5aRguyjpvKDBjFl7E4E7mpdpzA3OjNxB96b3g6umFVxT8wuccU9PVSK7R9A
K1z3sM8Q8wKBgE6rKUhaEnRLuukwwuo9v9LvKuLpxuPQYUUZYtuUmaK6XLvWZjtB
23TkoMUq8+IvoErREVEUutAG8x7gtq+vtVJ21uawnMnUxuhMBnNYzylrL3KUsI0G
WJ6l8fayEUa8ll4CTlAbk226VHD20qhsPCCB3+vATbcxGgvWwnsGcVHBAoGAdUzX
AyUzufnDEDNOLLOt5ZWdDNS3wO2673ysAgdBMO8yJm7KBtylhFDHYQBeAOLhAibQ
6gTSJTE7pyHq62X60Ml1TdZ5paZLIrz6aT9m9c25MPCkiPC/bD13PtPOff5ZJxVr
ixy3pMfg04AZBgXTLzoyGEKXlr5zWo3/hHOW/pUCgYEA2cH2uPNESzRjcDtiOfL4
U7tUpwiSLunTUfxTs7AXtP49lIPf3cRGqXwbIpVrQXYgZZbuKIMKwD3bloglFrEw
s9wEH2zQ1FXB1Wl5Z+/0YaX+aGd3weFw0alRmpLyGG7mWqRz0vzHBpnXF/iWry34
HY9YzxlHlf2yOHC1CqOrtxM=
-----END PRIVATE KEY-----"""
client_email = "mr-credencial-conta-serv@mr-league-cloud.iam.gserviceaccount.com"
client_id = "113573690172282462728"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mr-credencial-conta-serv%40mr-league-cloud.iam.gserviceaccount.com"
